#!/bin/bash

has_script_path=false

i=0
for arg in "$@"
do
    i=$((i+1))
    case "$arg" in
        --) : ${split_pos:=$i} ;;
        run) is_run=true ;;
        --script_path) has_script_path=true ;;
    esac
done

if [ -n "${split_pos:-}" ]
then
    extra_args=( "${@:$split_pos:$#}" )
    set -- "${@:1:$split_pos-1}"
fi

if [ "$is_run" = true -a "$has_script_path" = false ]
then
    runcmd="$(mktemp /tmp/bazel-run.XXXXXX)"
    set -- "$@" --script_path="$runcmd"
fi

test -n "${split_pos:-}" && set -- "$@" "${extra_args[@]}"

"$BAZEL_REAL" "$@"

if [ "$is_run" = true -a "$has_script_path" = false ]
then
    exec "$runcmd"
fi
